services:
  app:
    container_name: app
    restart: always
    build: ./dockersrc-app
    ports:
      - "5000:8000"
    depends_on:
      - db

  db:
    image: "postgres:16.4-alpine"
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "jetforgeapp"
      POSTGRES_PASSWORD: "43STdyJaf41sAsbKd"
      POSTGRES_DB: "jetforgedb"
